### ISSUE TITLE
The test from this repo does not pass

### ISSUE THREAD

**Issue by OlivierNicole** [o1-labs/integers_stubs_js#9]
```
$ dune build ./test/test.bc.js
$ node _build/default/test/test.bc.js
UInt8

x_64, y_64, z, z_64, M.of_int64, Done
Checking::: 254 = 254? 254 = 254? 0

x_64, y_64, z, z_64, M.of_int64, Done
Checking::: 254 = 254? 254 = 254? 0

[...]

x_64, y_64, z, z_64, M.of_int64, Done
Checking::: 4294967294 = 4294967294? 4294967294 = 4294967294? 0
Checking::: 4294967294 = 4294967294? 4294967294 = 4294967294? 0
Checking::: 510 = 510? 510 = 510? 0
Checking::: 131070 = 131070? 131070 = 131070? 0
Checking::: 33554430 = 33554430? 33554430 = 33554430? 0
Checking::: 4294967294 = 4294967294? 4294967294 = 4294967294? 0
UInt64

x_64, y_64, z, z_64, M.of_int64, Done
Checking::: 9223372036854775803 = -4? 9223372036854775803 = 18446744073709551612? 1
Fatal error: exception Failure("File "test/test.ml", line 55, characters 7-14")
/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:6772
      if(err.js_error) throw err.js_error;
                       ^

Error: Js exception containing backtrace
    at caml_exn_with_js_backtrace (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:283:21)
    at caml_maybe_attach_backtrace (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:288:15)
    at failwith (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:10940:11)
    at caml_call1 (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:25502:15)
    at check (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:25643:19)
    at caml_call1 (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:12773:15)
    at iter (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:12981:6)
    at caml_call2 (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:25507:15)
    at test_module (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:25645:5)
    at /home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:25709:4

Node.js v20.11.0
```

The failure apparently happens when running the `check` function on `-1L, -1L`:
https://github.com/o1-labs/integers_stubs_js/blob/141e0bc03a20b251edd97f4b320cc76db7fac291/test/test.ml#L55

**Comment by OlivierNicole** [comment]
> ```
> $ dune build ./test/test.bc.js
> $ node _build/default/test/test.bc.js
> UInt8
> 
> x_64, y_64, z, z_64, M.of_int64, Done
> Checking::: 254 = 254? 254 = 254? 0
> 
> x_64, y_64, z, z_64, M.of_int64, Done
> Checking::: 254 = 254? 254 = 254? 0
> 
> [...]
> 
> x_64, y_64, z, z_64, M.of_int64, Done
> Checking::: 4294967294 = 4294967294? 4294967294 = 4294967294? 0
> Checking::: 4294967294 = 4294967294? 4294967294 = 4294967294? 0
> Checking::: 510 = 510? 510 = 510? 0
> Checking::: 131070 = 131070? 131070 = 131070? 0
> Checking::: 33554430 = 33554430? 33554430 = 33554430? 0
> Checking::: 4294967294 = 4294967294? 4294967294 = 4294967294? 0
> UInt64
> 
> x_64, y_64, z, z_64, M.of_int64, Done
> Checking::: 9223372036854775803 = -4? 9223372036854775803 = 18446744073709551612? 1
> Fatal error: exception Failure("File "test/test.ml", line 55, characters 7-14")
> /home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:6772
>       if(err.js_error) throw err.js_error;
>                        ^
> 
> Error: Js exception containing backtrace
>     at caml_exn_with_js_backtrace (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:283:21)
>     at caml_maybe_attach_backtrace (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:288:15)
>     at failwith (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:10940:11)
>     at caml_call1 (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:25502:15)
>     at check (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:25643:19)
>     at caml_call1 (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:12773:15)
>     at iter (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:12981:6)
>     at caml_call2 (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:25507:15)
>     at test_module (/home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:25645:5)
>     at /home/olivier/ocaml_package_repos/integers_stubs_js/_build/default/test/test.bc.js:25709:4
> 
> Node.js v20.11.0
> ```
> 
> The failure apparently happens when running the `check` function on `-1L, -1L` and comparing against the `Int64` module:
> 
> https://github.com/o1-labs/integers_stubs_js/blob/141e0bc03a20b251edd97f4b320cc76db7fac291/test/test.ml#L55
